apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: dmqku6031-nodejs
  janus-idp.io/tekton: dmqku6031-nodejs
  backstage.io/kubernetes-id: dmqku6031-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: dmqku6031-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
