apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: dmqku6031-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: dmqku6031-nodejs 
  name: dmqku6031-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: dmqku6031-nodejs 
